[package]
name    = "bench"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
lisp   = { path = "../lisp" }
runes  = { path = "../runes" }
codons = { path = "../codons" }
spells = { path = "../spells" }
genes  = { path = "../genes" }

[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name    = "core"
harness = false

[[bench]]
name    = "demos"
harness = false
